# Generated by Django 5.1.4 on 2024-12-20 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the role', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the role', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, help_text='Upload the organization logo', null=True, upload_to='logos/')),
                ('name', models.CharField(help_text='Name of the organization', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the organization', null=True)),
                ('established_date', models.DateField(blank=True, help_text='Date the organization was established', null=True)),
                ('website', models.URLField(blank=True, help_text='Website URL of the organization', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for the organization', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Contact email address for the organization', max_length=254, null=True)),
                ('address', models.CharField(blank=True, help_text='Physical address of the organization', max_length=255, null=True)),
                ('mission_statement', models.TextField(blank=True, help_text='Mission statement of the organization', null=True)),
                ('vision_statement', models.TextField(blank=True, help_text='Vision statement of the organization', null=True)),
                ('industry', models.CharField(blank=True, help_text='Industry in which the organization operates', max_length=100, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutOrganization',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('overview', models.TextField(blank=True, help_text='Brief overview of the organization', null=True)),
                ('history', models.TextField(blank=True, help_text='Historical background of the organization', null=True)),
                ('core_values', models.TextField(blank=True, help_text='Core values of the organization', null=True)),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements of the organization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the about section was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the about section was last updated')),
                ('logo', models.ImageField(blank=True, help_text='Upload an image representing the organization', null=True, upload_to='logos/')),
                ('banner_image', models.ImageField(blank=True, help_text='Upload a banner image for the about section', null=True, upload_to='banners/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_organizations', to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_organizations', to='organization.organizationdetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSocialMedia',
            fields=[
                ('org_social_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(help_text='Name of the social media platform', max_length=50)),
                ('url', models.URLField(help_text='URL of the social media profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the link was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date the link was last updated')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='organization.organizationdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTeamMember',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, help_text='Short biography of the team member', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Upload member photo', null=True, upload_to='team_photos/')),
                ('start_date', models.DateField(blank=True, help_text='Date the team member started with the organization', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date the team member left the organization', null=True)),
                ('linked_in_profile', models.URLField(blank=True, help_text='LinkedIn profile URL of the team member', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for the team member', max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp contact number for the team member', max_length=15)),
                ('instagram_username', models.CharField(blank=True, help_text='Instagram username of the team member', max_length=100)),
                ('facebook_profile_url', models.URLField(blank=True, help_text='Facebook profile URL of the team member', null=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='organization.organizationdetails')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organizationrole')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTermsAndConditions',
            fields=[
                ('terms_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, help_text='Content of the terms and conditions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the terms were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the terms were last updated')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='organization.organizationdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
