# Generated by Django 5.1.4 on 2024-12-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutorganization',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='aboutorganization',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='organizationdetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='organizationsocialmedia',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationsocialmedia',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='organizationteammember',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationteammember',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='organizationteammember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='organizationtermsandconditions',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
