# Generated by Django 5.1.4 on 2024-12-20 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the ad', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the ad')),
                ('image', models.ImageField(blank=True, help_text='Upload an image representing the ad', null=True, upload_to='ads/images/')),
                ('url', models.URLField(help_text="URL for the ad's landing page")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the ad was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the ad was last updated')),
                ('status', models.CharField(default='Active', help_text='Status of the ad (e.g., Active, Inactive)', max_length=20)),
                ('start_date', models.DateTimeField(help_text='Date when the ad starts displaying')),
                ('end_date', models.DateTimeField(help_text='Date when the ad stops displaying')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
