# Generated by Django 5.1.4 on 2024-12-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='user_id',
            new_name='user',
        ),
    ]
