# Generated by Django 5.1.4 on 2024-12-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the person making the enquiry', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the person making the enquiry', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for the person', max_length=15)),
                ('subject', models.CharField(help_text='Subject of the enquiry', max_length=150)),
                ('message', models.TextField(help_text='Detailed message of the enquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the enquiry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the enquiry was last updated')),
                ('status', models.CharField(default='Pending', help_text='Status of the enquiry (e.g., Pending, Responded)', max_length=20)),
            ],
        ),
    ]
