# Generated by Django 5.1.4 on 2024-12-20 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('apartment', 'Apartment'), ('condo', 'Condo'), ('house', 'House'), ('industrial', 'Industrial'), ('villa', 'Villa')], max_length=20)),
                ('status', models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Street address', max_length=255)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('zip_code', models.CharField(help_text='Zip code', max_length=20)),
                ('state', models.CharField(help_text='State name', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for location', max_digits=9, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenities_title', models.DateField(max_length=255)),
                ('amenities_description', models.TextField()),
                ('amenities_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListingDetail',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(help_text='Size in square feet')),
                ('bedrooms', models.IntegerField(help_text='Number of bedrooms')),
                ('kitchens', models.IntegerField(help_text='Number of kitchens')),
                ('store_rooms', models.IntegerField(help_text='Number of store rooms')),
                ('halls', models.IntegerField(help_text='Number of halls')),
                ('floors_no', models.IntegerField(help_text='Number of floors')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_details', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_title', models.CharField(blank=True, help_text='Title for the image', max_length=255, null=True)),
                ('image_url', models.URLField(help_text='URL for the image')),
                ('video_upload', models.URLField(blank=True, help_text='URL for the uploaded video', null=True)),
                ('video_title', models.CharField(blank=True, help_text='Title for the video', max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='property.property')),
            ],
        ),
    ]
