# Generated by Django 5.1.4 on 2024-12-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenities_description',
        ),
        migrations.RemoveField(
            model_name='propertyamenities',
            name='amenities_title',
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='ac',
            field=models.BooleanField(default=False, help_text='A/C available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='barbecue',
            field=models.BooleanField(default=False, help_text='Barbecue available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ceiling height in feet', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='disabled_access',
            field=models.BooleanField(default=False, help_text='Disabled access available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='elevator',
            field=models.BooleanField(default=False, help_text='Elevator available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='garage',
            field=models.BooleanField(default=False, help_text='Garage available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='garden',
            field=models.BooleanField(default=False, help_text='Garden available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='heating',
            field=models.BooleanField(default=False, help_text='Heating available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='lake_view',
            field=models.BooleanField(default=False, help_text='Lake view available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='laundry_dryer',
            field=models.BooleanField(default=False, help_text='Laundry dryer available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='lawn',
            field=models.BooleanField(default=False, help_text='Lawn available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='lift',
            field=models.BooleanField(default=False, help_text='Lift available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='outdoor_shower',
            field=models.BooleanField(default=False, help_text='Outdoor shower available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='parking',
            field=models.BooleanField(default=False, help_text='Parking available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='pet_friendly',
            field=models.BooleanField(default=False, help_text='Pet friendly'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='refrigerator',
            field=models.BooleanField(default=False, help_text='Refrigerator available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='swimming_pool',
            field=models.BooleanField(default=False, help_text='Swimming pool available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='tv_cable',
            field=models.BooleanField(default=False, help_text='Cable TV available'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='wifi',
            field=models.BooleanField(default=False, help_text='Wi-Fi available'),
        ),
    ]
