# Generated by Django 5.1.4 on 2024-12-27 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_propertyamenities_amenities_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 5, 20, 40, 636917, tzinfo=datetime.timezone.utc)),
        ),
    ]
