# Generated by Django 5.1.4 on 2024-12-24 06:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_propertyamenities_amenities_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented'), ('liked', 'Liked')], max_length=10),
        ),
        migrations.CreateModel(
            name='PropertyCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('coupon_type', models.CharField(choices=[('FLAT', 'Flat Discount'), ('PERCENT', 'Percentage Discount'), ('BOGO', 'Buy One Get One Free')], default='FLAT', max_length=10)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2025, 1, 23, 6, 50, 17, 386880, tzinfo=datetime.timezone.utc))),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('property_enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the person making the enquiry', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the person making the enquiry', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for the person', max_length=15)),
                ('subject', models.CharField(help_text='Subject of the enquiry', max_length=150)),
                ('message', models.TextField(help_text='Detailed message of the enquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the enquiry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the enquiry was last updated')),
                ('status', models.CharField(default='Pending', help_text='Status of the enquiry (e.g., Pending, Responded)', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_enquiry', to='property.property')),
            ],
        ),
    ]
