# Generated by Django 5.1.4 on 2024-12-24 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_status_propertycoupon_propertyenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 6, 53, 30, 344329, tzinfo=datetime.timezone.utc)),
        ),
    ]
