# Generated by Django 5.1.4 on 2024-12-24 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertycoupon_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 6, 57, 9, 902076, tzinfo=datetime.timezone.utc)),
        ),
    ]
