# Generated by Django 5.1.4 on 2024-12-26 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertyenquiry_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymedia',
            name='video_upload',
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 9, 42, 42, 127309, tzinfo=datetime.timezone.utc)),
        ),
    ]
