# Generated by Django 5.1.4 on 2024-12-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertycoupon_valid_until'),
        ('property', '0006_propertyenquiry_customer_and_more'),
    ]

    operations = [
    ]
