# Generated by Django 5.1.4 on 2024-12-26 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_propertymedia_video_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 9, 58, 3, 482161, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
