# Generated by Django 5.1.4 on 2024-12-27 05:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_merge_20241227_1108'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymedia',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='propertymedia',
            name='video_upload',
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 5, 23, 23, 440836, tzinfo=datetime.timezone.utc)),
        ),
    ]
