# Generated by Django 5.1.4 on 2024-12-27 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_propertymedia_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 5, 23, 28, 929362, tzinfo=datetime.timezone.utc)),
        ),
    ]
