# Generated by Django 5.1.4 on 2024-12-26 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_propertycoupon_valid_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylistingdetail',
            name='halls',
        ),
        migrations.AddField(
            model_name='propertylistingdetail',
            name='bathroom',
            field=models.IntegerField(default=1, help_text='Number of bathrooms'),
        ),
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 10, 15, 13, 6644, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='property_image'),
        ),
    ]
