# Generated by Django 5.1.4 on 2024-12-31 07:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_propertycoupon_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(limit_choices_to=models.Q(('user_type', 'agent'), ('user_type', 'admin'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 7, 49, 13, 594355, tzinfo=datetime.timezone.utc)),
        ),
    ]
