# Generated by Django 5.1.4 on 2024-12-31 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycoupon',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 11, 18, 44, 547954, tzinfo=datetime.timezone.utc)),
        ),
    ]
